version: '2'
services:
  recommendation:
    image: recommendation
    build: recommendation-service/
    container_name: recommendation
    network_mode: host
    ports:
      - 8086:8080
    expose:
      - 8086
